name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0" # every Sunday at midnight
  workflow_dispatch:

jobs:
  industrial_ci:
    if: github.event.pull_request.draft == false  # only run on non-draft PRs
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      ADDITIONAL_DEBS: 'apt-utils dialog'
      AFTER_SCRIPT: 'rosenv bash .travis.xacro_test.sh'
      CATKIN_LINT: pedantic
      CATKIN_LINT_ARGS: '--ignore description_boilerplate'
      CMAKE_ARGS: -DCMAKE_BUILD_TYPE=Release
      PYLINT_ARGS: '--output-format=parseable --errors-only'
      PYLINT_CHECK: true
      ROS_REPO: main

    strategy:
      matrix:
        include:
          # - { ROS_DISTRO: kinetic }
          - { ROS_DISTRO: noetic }

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          ssh-known-hosts: ''

      - uses: ros-industrial/industrial_ci@master
        with:
          config: ${{toJSON(matrix)}}
